# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceOptions.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rpc.ServiceOption" do
    optional :id, :uint32, 1
    optional :warehouse_location_id, :uint32, 2
    optional :start_at, :string, 3
    optional :end_at, :string, 4
    optional :window_description, :string, 5
  end
  add_message "rpc.GetServiceOptionsReq" do
  end
end

module Rpc
  ServiceOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ServiceOption").msgclass
  GetServiceOptionsReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetServiceOptionsReq").msgclass
end
