# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ServiceOptions.proto for package 'rpc'

require 'grpc'
require 'ServiceOptions_pb'

module Rpc
  module ServiceOptions
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.ServiceOptions'

      rpc :GetServiceOptions, GetServiceOptionsReq, stream(ServiceOption)
    end

    Stub = Service.rpc_stub_class
  end
end
